name: muscle_boy
description: muscle boy app.
publish_to:
version: 0.1.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.20


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  simple_logger: ^1.9.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/sounds/
